/**
 * AUTO-GENERATED by scripts/sync-naval-rich.mjs — do not edit by hand.
 * Source: https://nav.al/rich
 * Synced: 2026-07-11T17:49:57.110Z
 */

export const NAVAL_RICH_SOURCE_URL = 'https://nav.al/rich';

export interface NavalRichLevel {
  level: number;
  tweet: string;
  sectionTitle: string;
  sectionIndex: number;
  navAlAnchor: string;
  taglines: string[];
  navalQuotes: string[];
  niviQuotes: string[];
  tweetQuotesFromDialogue: string[];
}

export const NAVAL_RICH_LEVELS: NavalRichLevel[] = [
  {
    "level": 1,
    "tweet": "Seek wealth, not money or status. Wealth is having assets that earn while you sleep. Money is how we transfer time and wealth. Status is your place in the social hierarchy.",
    "sectionTitle": "Seek Wealth, Not Money or Status",
    "sectionIndex": 0,
    "navAlAnchor": "#seek-wealth-not-money-or-status",
    "taglines": [
      "Wealth is assets that earn while you sleep",
      "Naval is a prolific tech investor and founder of AngelList",
      "Wealth buys your freedom",
      "Money is how we transfer wealth",
      "Status is your rank in the social hierarchy",
      "Status is a very old game"
    ],
    "navalQuotes": [
      "The \"How to Get Rich\" tweetstorm definitely hit a nerve and went viral. A lot of people say it was helpful and reached across aisles.",
      "Wealth is the thing you want. Wealth is assets that earn while you sleep; it's the factory of robots cranking out things. Wealth is the computer program running at night that's serving other customers. Wealth is money in the bank that is reinvested into other assets and businesses."
    ],
    "niviQuotes": [
      "You probably know Naval from his Twitter account.",
      "What's the difference between wealth, money and status?"
    ],
    "tweetQuotesFromDialogue": [
      "How to Get Rich"
    ]
  },
  {
    "level": 2,
    "tweet": "Understand that ethical wealth creation is possible. If you secretly despise wealth, it will elude you.",
    "sectionTitle": "Make Abundance for the World",
    "sectionIndex": 1,
    "navAlAnchor": "#make-abundance-for-the-world",
    "taglines": [
      "Ethical wealth creation makes abundance for the world",
      "Everyone can be rich"
    ],
    "navalQuotes": [
      "I think there is this notion that making money is evil, right? It's rooted all the way back down to “money is the root of all evil.” People think that the bankers steal our money. It's somewhat true in that, in a lot of the world, there's a lot of theft going on all the time."
    ],
    "niviQuotes": [],
    "tweetQuotesFromDialogue": [
      "money is the root of all evil."
    ]
  },
  {
    "level": 3,
    "tweet": "Ignore people playing status games. They gain status by attacking people playing wealth creation games.",
    "sectionTitle": "Seek Wealth, Not Money or Status",
    "sectionIndex": 0,
    "navAlAnchor": "#seek-wealth-not-money-or-status",
    "taglines": [
      "Wealth is assets that earn while you sleep",
      "Naval is a prolific tech investor and founder of AngelList",
      "Wealth buys your freedom",
      "Money is how we transfer wealth",
      "Status is your rank in the social hierarchy",
      "Status is a very old game"
    ],
    "navalQuotes": [
      "The \"How to Get Rich\" tweetstorm definitely hit a nerve and went viral. A lot of people say it was helpful and reached across aisles.",
      "Wealth is the thing you want. Wealth is assets that earn while you sleep; it's the factory of robots cranking out things. Wealth is the computer program running at night that's serving other customers. Wealth is money in the bank that is reinvested into other assets and businesses."
    ],
    "niviQuotes": [
      "You probably know Naval from his Twitter account.",
      "What's the difference between wealth, money and status?"
    ],
    "tweetQuotesFromDialogue": [
      "How to Get Rich"
    ]
  },
  {
    "level": 4,
    "tweet": "You're not going to get rich renting out your time. You must own equity — a piece of a business — to gain your financial freedom.",
    "sectionTitle": "You Won't Get Rich Renting Out Your Time",
    "sectionIndex": 5,
    "navAlAnchor": "#you-wont-get-rich-renting-out-your-time",
    "taglines": [
      "You can't earn non-linearly when you're renting out your time",
      "You won't get rich renting out your time"
    ],
    "navalQuotes": [
      "This is probably one of the absolute most important points. People seem to think that you can create wealth, and make money through work. And it's probably not going to work. There are many reasons for that."
    ],
    "niviQuotes": [
      "Next you go into more specific details on how you can actually get rich, and how you can't get rich. The first point was about how you're not going to get rich: “You are not going to get rich renting out your time. You must own equity, a piece of the business to gain your financial freedom.”"
    ],
    "tweetQuotesFromDialogue": [
      "You are not going to get rich renting out your time. You must own equity, a piece of the business to gain your financial freedom."
    ]
  },
  {
    "level": 5,
    "tweet": "You will get rich by giving society what it wants but does not yet know how to get. At scale.",
    "sectionTitle": "Give Society What It Doesn't Know How to Get",
    "sectionIndex": 7,
    "navAlAnchor": "#give-society-what-it-doesnt-know-how-to-get",
    "taglines": [
      "Society will pay you for creating what it wants and delivering it at scale",
      "Give society what it wants, but doesn't know how to get—at scale",
      "Figure out what product you can provide and then figure out how to scale it"
    ],
    "navalQuotes": [
      "That's right. So, essentially as we talked about before, money is IOUs from society saying, “You did something good in the past. Now here's something that we owe you for the future.” And so society will pay you for creating things that it wants.",
      "It starts as high end. First it starts as an act of creativity. First you create it just because you want it. You want it, and you know how to build it, and you need it. And so you build it for yourself. Then you figure out how to get it to other people. And then for a little while rich people have it."
    ],
    "niviQuotes": [
      "You're not gonna get rich renting out your time. But you say that, “you will get rich by giving society what it wants, but does not yet know how to get at scale.”",
      "The way I tried to put it was that the entrepreneur's job is to try to bring the high end to the mass market."
    ],
    "tweetQuotesFromDialogue": [
      "you will get rich by giving society what it wants, but does not yet know how to get at scale.",
      "You did something good in the past. Now here's something that we owe you for the future."
    ]
  },
  {
    "level": 6,
    "tweet": "Pick an industry where you can play long-term games with long-term people.",
    "sectionTitle": "Play Long-Term Games With Long-Term People",
    "sectionIndex": 9,
    "navAlAnchor": "#play-long-term-games-with-long-term-people",
    "taglines": [
      "All returns in life come from compound interest in long-term games"
    ],
    "navalQuotes": [
      "Yeah, this is an insight into what makes Silicon Valley work, and what makes high trust societies work. Essentially, all the benefits in life come from compound interests. Whether it's in relationships, or making money, or in learning.",
      "I think that is a brilliant formulation. In a longterm game, it's positive sum. We're all baking the pie together. We're trying to make it as big as possible. And in a short term game, we're cutting up the pie.",
      "When you have been doing business with somebody, you've been friends with somebody for ten years, twenty years, thirty years, it just gets better and better because you trust them so easily. The friction goes down, you can do bigger, and bigger things together."
    ],
    "niviQuotes": [
      "Talk a little bit about what industries you should think about working in. What kind of job you should have? And who you might want to work with? So, you said, “One should pick an industry where you can play long-term games with long-term people.” Why?",
      "In a long-term game, it seems that everybody is making each other rich. And in a short-term game, it seems like everybody is making themselves rich."
    ],
    "tweetQuotesFromDialogue": [
      "One should pick an industry where you can play long-term games with long-term people.",
      "Play iterated games. All returns in life, whether in wealth, relationships, or knowledge come from compound interest.",
      "Get some traction. Get purchase, and don't lose it"
    ]
  },
  {
    "level": 7,
    "tweet": "The Internet has massively broadened the possible space of careers. Most people haven't figured this out yet.",
    "sectionTitle": "The Internet Has Massively Broadened Career Possibilities",
    "sectionIndex": 8,
    "navAlAnchor": "#the-internet-has-massively-broadened-career-possibilities",
    "taglines": [
      "The Internet allows you to scale any niche obsession"
    ],
    "navalQuotes": [
      "The fundamental property of the internet more than any other single thing is it connects every human to each other human on the planet. You can now reach everyone."
    ],
    "niviQuotes": [
      "Let's look at this next tweet, which I thought was cryptic, and also super interesting, about the kind of job or career that you might have. You said, “The internet has massively broadened the possible space of careers. Most people haven't figured this out yet.”"
    ],
    "tweetQuotesFromDialogue": [
      "The internet has massively broadened the possible space of careers. Most people haven't figured this out yet."
    ]
  },
  {
    "level": 8,
    "tweet": "Play iterated games. All the returns in life, whether in wealth, relationships, or knowledge, come from compound interest.",
    "sectionTitle": "Play Long-Term Games With Long-Term People",
    "sectionIndex": 9,
    "navAlAnchor": "#play-long-term-games-with-long-term-people",
    "taglines": [
      "All returns in life come from compound interest in long-term games"
    ],
    "navalQuotes": [
      "Yeah, this is an insight into what makes Silicon Valley work, and what makes high trust societies work. Essentially, all the benefits in life come from compound interests. Whether it's in relationships, or making money, or in learning.",
      "I think that is a brilliant formulation. In a longterm game, it's positive sum. We're all baking the pie together. We're trying to make it as big as possible. And in a short term game, we're cutting up the pie.",
      "When you have been doing business with somebody, you've been friends with somebody for ten years, twenty years, thirty years, it just gets better and better because you trust them so easily. The friction goes down, you can do bigger, and bigger things together."
    ],
    "niviQuotes": [
      "Talk a little bit about what industries you should think about working in. What kind of job you should have? And who you might want to work with? So, you said, “One should pick an industry where you can play long-term games with long-term people.” Why?",
      "In a long-term game, it seems that everybody is making each other rich. And in a short-term game, it seems like everybody is making themselves rich."
    ],
    "tweetQuotesFromDialogue": [
      "One should pick an industry where you can play long-term games with long-term people.",
      "Play iterated games. All returns in life, whether in wealth, relationships, or knowledge come from compound interest.",
      "Get some traction. Get purchase, and don't lose it"
    ]
  },
  {
    "level": 9,
    "tweet": "Pick business partners with high intelligence, energy, and, above all, integrity.",
    "sectionTitle": "Pick Partners With Intelligence, Energy and Integrity",
    "sectionIndex": 10,
    "navAlAnchor": "#pick-partners-with-intelligence-energy-and-integrity",
    "taglines": [
      "You can't compromise on any of these three"
    ],
    "navalQuotes": [
      "In terms of picking people to work with, pick ones that have high intelligence, high energy, and high integrity, I find that's the three-part checklist that you cannot compromise on.",
      "Yeah. I almost won't start a company, or hire a person, or work with somebody if I just don't think they're into what I want them to do."
    ],
    "niviQuotes": [
      "With respect to the energy, there was this interesting thing from Sam Altman a while back, where he was talking about delegation, and he was saying, “One of the important things for delegation is, delegate to people who are actually good at the thing that you want them to do.”"
    ],
    "tweetQuotesFromDialogue": [
      "One of the important things for delegation is, delegate to people who are actually good at the thing that you want them to do."
    ]
  },
  {
    "level": 10,
    "tweet": "Don't partner with cynics and pessimists. Their beliefs are self-fulfilling.",
    "sectionTitle": "Partner With Rational Optimists",
    "sectionIndex": 11,
    "navAlAnchor": "#partner-with-rational-optimists",
    "taglines": [
      "Don't partner with cynics and pessimists; their beliefs are self-fulfilling"
    ],
    "navalQuotes": [
      "Yes. Essentially, to create things, you have to be a rational optimist. Rational in the sense that you have to see the world for what it really is. And yet you have to be optimistic about your own capabilities, and your capability to get things done.",
      "There's a completely rational frame on why you should be an optimist. Historically, if you go back 2,000 years, 5,000 years, 10,000 years, two people are wandering through a jungle, they hear a tiger. One's an optimist, and says, “Oh, it's not headed our way.” The other one says, “I'm a pessimist, I'm out of here.” And the pessimist runs and survives, and the optimist gets eaten.",
      "That's what Twitter is for. Scott Adams got so annoyed by this that he came up with a phrase, an acronym, which is “but of course there are obvious exceptions”, BOCTAOE. And he used to pin that acronym at the end of his articles for a while."
    ],
    "niviQuotes": [
      "Let's do this last tweet. You said, “Don't partner with cynics, and pessimists. Their beliefs are self-fulfilling.”",
      "Yes, it's probably better to be an irrational optimist, then it is to be a rational cynic."
    ],
    "tweetQuotesFromDialogue": [
      "Don't partner with cynics, and pessimists. Their beliefs are self-fulfilling.",
      "Oh, it's not headed our way.",
      "I'm a pessimist, I'm out of here."
    ]
  },
  {
    "level": 11,
    "tweet": "Learn to sell. Learn to build. If you can do both, you will be unstoppable.",
    "sectionTitle": "Learn to Sell, Learn to Build",
    "sectionIndex": 14,
    "navAlAnchor": "#learn-to-sell-learn-to-build",
    "taglines": [
      "If you can do both, you will be unstoppable"
    ],
    "navalQuotes": [
      "This is a very broad category. It's two broad categories. One is building the product. Which is hard, and it's multivariate. It can include design, it can include development, it can include manufacturing, logistics, procurement, it can even be designing and operating a service. It has many, many definitions.",
      "When you're trying to stand out from the noise building is actually better because there're so many hustlers and sales people who have nothing to back them up. When you're starting out, when you're trying to be recognized, building is better."
    ],
    "niviQuotes": [
      "Talking about combining skills, you said that you should “learn to sell, learn to build, if you can do both, you will be unstoppable.”",
      "If you could only pick one to be good at, which one would you pick?"
    ],
    "tweetQuotesFromDialogue": [
      "learn to sell, learn to build, if you can do both, you will be unstoppable."
    ]
  },
  {
    "level": 12,
    "tweet": "Arm yourself with specific knowledge, accountability, and leverage.",
    "sectionTitle": "Arm Yourself With Specific Knowledge",
    "sectionIndex": 12,
    "navAlAnchor": "#arm-yourself-with-specific-knowledge",
    "taglines": [
      "Specific knowledge can be found by pursuing your genuine curiosity",
      "Arm yourself with specific knowledge"
    ],
    "navalQuotes": [
      "If you want to make money you have to get paid at scale. And why you, that's accountability, at scale, that's leverage, and just you getting paid as opposed to somebody else getting paid , that's specific knowledge."
    ],
    "niviQuotes": [
      "Do you want to talk a little bit about the skills that you need, in particular specific knowledge, accountability, leverage and judgment. So, the first tweet in this area is “Arm yourself with specific knowledge accountability and leverage.” And I'll throw in judgment as well. I don't think you covered that in that particular tweet."
    ],
    "tweetQuotesFromDialogue": [
      "Arm yourself with specific knowledge accountability and leverage."
    ]
  },
  {
    "level": 13,
    "tweet": "Specific knowledge is knowledge that you cannot be trained for. If society can train you, it can train someone else, and replace you.",
    "sectionTitle": "Specific Knowledge Is Highly Creative or Technical",
    "sectionIndex": 13,
    "navAlAnchor": "#specific-knowledge-is-highly-creative-or-technical",
    "taglines": [
      "Specific knowledge is on the bleeding edge of technology, art and communication",
      "Specific knowledge can be taught through apprenticeships",
      "Specific knowledge is often highly creative or technical",
      "Specific knowledge is specific to the individual and situation",
      "You can't be too deliberate about assembling specific knowledge",
      "Build specific knowledge where you are a natural"
    ],
    "navalQuotes": [
      "To the extent that specific knowledge is taught, it's on the job. It's through apprenticeships. And that's why the best businesses, the best careers are the apprenticeship or self-taught careers, because those are things society still has not figured out how to train and automate yet.",
      "You know, I came up with this framework when I was really young. We're talking decades and decades. It's now probably over 30 years old. So, at the time specific knowledge stuck with me so that is how I think about it.",
      "I actually think the best way is just to follow your own obsession. And somewhere in the back of your mind, you can realize that, actually, this obsession I like and I'll keep an eye out for the commercial aspects of it."
    ],
    "niviQuotes": [
      "Should we be calling it unique knowledge or does specific knowledge somehow make more sense for it?",
      "Speaking of Scott Adams, he's got a blog post on how to build your career by getting in, say, the top 25 percentile at three or more things. And by doing that, you become the only person in the world who can do those three things in the 25th percentile."
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 14,
    "tweet": "Specific knowledge is found by pursuing your genuine curiosity and passion rather than whatever is hot right now.",
    "sectionTitle": "Specific Knowledge Is Highly Creative or Technical",
    "sectionIndex": 13,
    "navAlAnchor": "#specific-knowledge-is-highly-creative-or-technical",
    "taglines": [
      "Specific knowledge is on the bleeding edge of technology, art and communication",
      "Specific knowledge can be taught through apprenticeships",
      "Specific knowledge is often highly creative or technical",
      "Specific knowledge is specific to the individual and situation",
      "You can't be too deliberate about assembling specific knowledge",
      "Build specific knowledge where you are a natural"
    ],
    "navalQuotes": [
      "To the extent that specific knowledge is taught, it's on the job. It's through apprenticeships. And that's why the best businesses, the best careers are the apprenticeship or self-taught careers, because those are things society still has not figured out how to train and automate yet.",
      "You know, I came up with this framework when I was really young. We're talking decades and decades. It's now probably over 30 years old. So, at the time specific knowledge stuck with me so that is how I think about it.",
      "I actually think the best way is just to follow your own obsession. And somewhere in the back of your mind, you can realize that, actually, this obsession I like and I'll keep an eye out for the commercial aspects of it."
    ],
    "niviQuotes": [
      "Should we be calling it unique knowledge or does specific knowledge somehow make more sense for it?",
      "Speaking of Scott Adams, he's got a blog post on how to build your career by getting in, say, the top 25 percentile at three or more things. And by doing that, you become the only person in the world who can do those three things in the 25th percentile."
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 15,
    "tweet": "Building specific knowledge will feel like play to you but will look like work to others.",
    "sectionTitle": "Specific Knowledge Is Highly Creative or Technical",
    "sectionIndex": 13,
    "navAlAnchor": "#specific-knowledge-is-highly-creative-or-technical",
    "taglines": [
      "Specific knowledge is on the bleeding edge of technology, art and communication",
      "Specific knowledge can be taught through apprenticeships",
      "Specific knowledge is often highly creative or technical",
      "Specific knowledge is specific to the individual and situation",
      "You can't be too deliberate about assembling specific knowledge",
      "Build specific knowledge where you are a natural"
    ],
    "navalQuotes": [
      "To the extent that specific knowledge is taught, it's on the job. It's through apprenticeships. And that's why the best businesses, the best careers are the apprenticeship or self-taught careers, because those are things society still has not figured out how to train and automate yet.",
      "You know, I came up with this framework when I was really young. We're talking decades and decades. It's now probably over 30 years old. So, at the time specific knowledge stuck with me so that is how I think about it.",
      "I actually think the best way is just to follow your own obsession. And somewhere in the back of your mind, you can realize that, actually, this obsession I like and I'll keep an eye out for the commercial aspects of it."
    ],
    "niviQuotes": [
      "Should we be calling it unique knowledge or does specific knowledge somehow make more sense for it?",
      "Speaking of Scott Adams, he's got a blog post on how to build your career by getting in, say, the top 25 percentile at three or more things. And by doing that, you become the only person in the world who can do those three things in the 25th percentile."
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 16,
    "tweet": "Embrace accountability, and take business risks under your own name. Society will reward you with responsibility, equity, and leverage.",
    "sectionTitle": "Embrace Accountability to Get Leverage",
    "sectionIndex": 18,
    "navAlAnchor": "#embrace-accountability-to-get-leverage",
    "taglines": [
      "Take risks under your own name and society will reward you with leverage"
    ],
    "navalQuotes": [
      "Yeah. So to get rich, you're going to need leverage. Leverage comes in labor, comes in capital, or it can come through code or media. But most of these, like labor and capital, people have to give to you. For labor, somebody has to follow you. For capital, somebody has to give you money or assets to manage or machines."
    ],
    "niviQuotes": [
      "Why don't we jump into accountability, which I thought was pretty interesting and I think you have your own unique take on it. So the first tweet on accountability was, “Embrace accountability and take business risks under your own name. Society will reward you with responsibility, equity, and leverage.”"
    ],
    "tweetQuotesFromDialogue": [
      "Embrace accountability and take business risks under your own name. Society will reward you with responsibility, equity, and leverage."
    ]
  },
  {
    "level": 17,
    "tweet": "Fortunes require leverage. Business leverage comes from capital, people, and products with no marginal cost of replication (code and media).",
    "sectionTitle": "Labor and Capital Are Old Leverage",
    "sectionIndex": 20,
    "navAlAnchor": "#labor-and-capital-are-old-leverage",
    "taglines": [
      "Everyone is fighting over labor and capital"
    ],
    "navalQuotes": [
      "Leverage is critical. The reason I stuck in Archimedes quote in there is… normally I don't like putting other people's quotes in my Twitter. That doesn't add any value. You can go look up those people's quotes. But this quote I had to put in there because it's just so fundamental. I read it when I was very, very young and it had a huge impression on me."
    ],
    "niviQuotes": [
      "Why don't we talk a little bit about leverage?"
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 18,
    "tweet": "Code and media are permissionless leverage. They're the leverage behind the newly rich. You can create software and media that works for you while you sleep.",
    "sectionTitle": "Product and Media Are New Leverage",
    "sectionIndex": 21,
    "navAlAnchor": "#product-and-media-are-new-leverage",
    "taglines": [
      "Create software and media that work for you while you sleep"
    ],
    "navalQuotes": [
      "The most interesting and the most important form of leverage is this idea of products that have no marginal cost of replication. This is the new form of leverage.",
      "Probably the most interesting thing to keep in mind about the new forms of leverage is they are permissionless. They don't require somebody else's permission for you to use them or succeed."
    ],
    "niviQuotes": [
      "Do you want to talk a little bit about permissioned versus permissionless?",
      "I think at this point, people are not only commanding the army of robots within servers through code, they're actually manipulating the movement of trucks, of other people. Just ordering a package on Amazon, you're manipulating the movement of many people and many robots to get a package delivered to you."
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 19,
    "tweet": "Set and enforce an aspirational personal hourly rate. If fixing a problem will save less than your hourly rate, ignore it. If outsourcing a task will cost less than your hourly rate, outsource it.",
    "sectionTitle": "Set an Aspirational Hourly Rate",
    "sectionIndex": 26,
    "navAlAnchor": "#set-an-aspirational-hourly-rate",
    "taglines": [
      "Outsource tasks that cost less than your hourly rate"
    ],
    "navalQuotes": [
      "No one is going to value you more than you value you. Set a high personal hourly rate, and stick to it. When I was young, I decided I was worth a lot more than the market thought I was worth. And I started treating myself that way."
    ],
    "niviQuotes": [
      "We covered the skills you need to get rich. They included specific knowledge, accountability, leverage, judgment and life-long learning. Let’s talk about the importance of working hard and valuing your time."
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 20,
    "tweet": "Become the best in the world at what you do. Keep redefining what you do until this is true.",
    "sectionTitle": "Keep Redefining What You Do",
    "sectionIndex": 29,
    "navAlAnchor": "#keep-redefining-what-you-do",
    "taglines": [
      "Find founder-product-market fit"
    ],
    "navalQuotes": [
      "If you really want to get paid in this world, you want to be number one at whatever you do. It can be niche—that’s the point. You can literally get paid for just being you."
    ],
    "niviQuotes": [
      "We talked about the importance of working hard and valuing your time. Next, there are a few tweets on the topic of working for the long-term. The first tweet is: “ Become the best in the world at what you do. Keep redefining what you do until this is true. ”"
    ],
    "tweetQuotesFromDialogue": [
      "Become the best in the world at what you do. Keep redefining what you do until this is true."
    ]
  },
  {
    "level": 21,
    "tweet": "Capital means money. To raise money, apply your specific knowledge, with accountability, and show resulting good judgment.",
    "sectionTitle": "Labor and Capital Are Old Leverage",
    "sectionIndex": 20,
    "navAlAnchor": "#labor-and-capital-are-old-leverage",
    "taglines": [
      "Everyone is fighting over labor and capital"
    ],
    "navalQuotes": [
      "Leverage is critical. The reason I stuck in Archimedes quote in there is… normally I don't like putting other people's quotes in my Twitter. That doesn't add any value. You can go look up those people's quotes. But this quote I had to put in there because it's just so fundamental. I read it when I was very, very young and it had a huge impression on me."
    ],
    "niviQuotes": [
      "Why don't we talk a little bit about leverage?"
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 22,
    "tweet": "Labor means people working for you. It's the oldest and most fought-over form of leverage. Labor leverage will impress your parents, but don't waste your life chasing it.",
    "sectionTitle": "Labor and Capital Are Old Leverage",
    "sectionIndex": 20,
    "navAlAnchor": "#labor-and-capital-are-old-leverage",
    "taglines": [
      "Everyone is fighting over labor and capital"
    ],
    "navalQuotes": [
      "Leverage is critical. The reason I stuck in Archimedes quote in there is… normally I don't like putting other people's quotes in my Twitter. That doesn't add any value. You can go look up those people's quotes. But this quote I had to put in there because it's just so fundamental. I read it when I was very, very young and it had a huge impression on me."
    ],
    "niviQuotes": [
      "Why don't we talk a little bit about leverage?"
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 23,
    "tweet": "Capital and labor are permissioned leverage. Everyone is chasing capital, but someone has to give it to you. Everyone is trying to lead, but someone has to follow you.",
    "sectionTitle": "Product and Media Are New Leverage",
    "sectionIndex": 21,
    "navAlAnchor": "#product-and-media-are-new-leverage",
    "taglines": [
      "Create software and media that work for you while you sleep"
    ],
    "navalQuotes": [
      "The most interesting and the most important form of leverage is this idea of products that have no marginal cost of replication. This is the new form of leverage.",
      "Probably the most interesting thing to keep in mind about the new forms of leverage is they are permissionless. They don't require somebody else's permission for you to use them or succeed."
    ],
    "niviQuotes": [
      "Do you want to talk a little bit about permissioned versus permissionless?",
      "I think at this point, people are not only commanding the army of robots within servers through code, they're actually manipulating the movement of trucks, of other people. Just ordering a package on Amazon, you're manipulating the movement of many people and many robots to get a package delivered to you."
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 24,
    "tweet": "Code and media are permissionless leverage. They're the leverage behind the newly rich. You can create software and media that works for you while you sleep.",
    "sectionTitle": "Product and Media Are New Leverage",
    "sectionIndex": 21,
    "navAlAnchor": "#product-and-media-are-new-leverage",
    "taglines": [
      "Create software and media that work for you while you sleep"
    ],
    "navalQuotes": [
      "The most interesting and the most important form of leverage is this idea of products that have no marginal cost of replication. This is the new form of leverage.",
      "Probably the most interesting thing to keep in mind about the new forms of leverage is they are permissionless. They don't require somebody else's permission for you to use them or succeed."
    ],
    "niviQuotes": [
      "Do you want to talk a little bit about permissioned versus permissionless?",
      "I think at this point, people are not only commanding the army of robots within servers through code, they're actually manipulating the movement of trucks, of other people. Just ordering a package on Amazon, you're manipulating the movement of many people and many robots to get a package delivered to you."
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 25,
    "tweet": "An army of robots is freely available — it's just packed in data centers for heat and space efficiency. Use it.",
    "sectionTitle": "Product Leverage is Egalitarian",
    "sectionIndex": 22,
    "navAlAnchor": "#product-leverage-is-egalitarian",
    "taglines": [
      "The best products tend to be available to everyone",
      "Creating wealth with product leads to more ethical wealth"
    ],
    "navalQuotes": [
      "Labor and capital are much less egalitarian, not just in the inputs, but in their outputs."
    ],
    "niviQuotes": [
      "People and capital as a form of leverage have a negative externality and code and product have a positive externality attached to them, if I was going to sum up your point."
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 26,
    "tweet": "If you can't code, write books and blogs, record videos and podcasts.",
    "sectionTitle": "Product Leverage is Egalitarian",
    "sectionIndex": 22,
    "navAlAnchor": "#product-leverage-is-egalitarian",
    "taglines": [
      "The best products tend to be available to everyone",
      "Creating wealth with product leads to more ethical wealth"
    ],
    "navalQuotes": [
      "Labor and capital are much less egalitarian, not just in the inputs, but in their outputs."
    ],
    "niviQuotes": [
      "People and capital as a form of leverage have a negative externality and code and product have a positive externality attached to them, if I was going to sum up your point."
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 27,
    "tweet": "Leverage is a force multiplier for your judgment.",
    "sectionTitle": "Judgment Is the Decisive Skill",
    "sectionIndex": 25,
    "navAlAnchor": "#judgment-is-the-decisive-skill",
    "taglines": [
      "In an age of nearly infinite leverage, judgment is the most important skill"
    ],
    "navalQuotes": [
      "We are now living in an age of nearly infinite leverage, and all the great fortunes are created through leverage. Your first job is to go and obtain leverage, and you can obtain leverage through permission by getting people to work for you, or by raising capital.",
      "It's funny. My definition of wisdom is knowing the long term consequences of your actions, so they're not all that different. Wisdom is just judgment on a personal domain.",
      "And the reason why a lot of the top investors, a lot of the value investors, like if you read Jeremy Grantham, or you read Warren Buffet, or you read up on Michael Burry, these people sound like philosophers, or they are philosophers, or they're reading a lot of history books or science books."
    ],
    "niviQuotes": [
      "We spoke about specific knowledge, we talked about accountability, we talked about leverage. The last skill that Naval talks about in his tweetstorm is judgment, where he says, that “Leverage is a force multiplier for your judgment.”",
      "Let's define judgment. I would define it as knowing the long-term effects of your decisions, or being able to predict the long-term effects of your decisions."
    ],
    "tweetQuotesFromDialogue": [
      "Leverage is a force multiplier for your judgment."
    ]
  },
  {
    "level": 28,
    "tweet": "Judgment requires experience, but can be built faster by learning foundational skills.",
    "sectionTitle": "Judgment Is the Decisive Skill",
    "sectionIndex": 25,
    "navAlAnchor": "#judgment-is-the-decisive-skill",
    "taglines": [
      "In an age of nearly infinite leverage, judgment is the most important skill"
    ],
    "navalQuotes": [
      "We are now living in an age of nearly infinite leverage, and all the great fortunes are created through leverage. Your first job is to go and obtain leverage, and you can obtain leverage through permission by getting people to work for you, or by raising capital.",
      "It's funny. My definition of wisdom is knowing the long term consequences of your actions, so they're not all that different. Wisdom is just judgment on a personal domain.",
      "And the reason why a lot of the top investors, a lot of the value investors, like if you read Jeremy Grantham, or you read Warren Buffet, or you read up on Michael Burry, these people sound like philosophers, or they are philosophers, or they're reading a lot of history books or science books."
    ],
    "niviQuotes": [
      "We spoke about specific knowledge, we talked about accountability, we talked about leverage. The last skill that Naval talks about in his tweetstorm is judgment, where he says, that “Leverage is a force multiplier for your judgment.”",
      "Let's define judgment. I would define it as knowing the long-term effects of your decisions, or being able to predict the long-term effects of your decisions."
    ],
    "tweetQuotesFromDialogue": [
      "Leverage is a force multiplier for your judgment."
    ]
  },
  {
    "level": 29,
    "tweet": "There is no skill called \"business.\" Avoid business magazines and business classes.",
    "sectionTitle": "There's No Actual Skill Called 'Business'",
    "sectionIndex": 17,
    "navAlAnchor": "#theres-no-actual-skill-called-business",
    "taglines": [
      "Avoid business schools and magazines"
    ],
    "navalQuotes": [
      "In that sense, business to me is bottom of the barrel. There's no actual skill called business, it's too generic. It's like a skill called \"relating.\" Like \"relating to humans.\" That's not a skill, it's too broad.",
      "When it comes to your learning curve, if you want to optimize your learning curve&#8230; One of the reasons why I don't love podcasts, even though I'm a generator of podcasts, is that I like to consume my information very quickly."
    ],
    "niviQuotes": [
      "What did you mean when you said that “doing is faster than watching?”"
    ],
    "tweetQuotesFromDialogue": [
      "relating to humans.",
      "doing is faster than watching?"
    ]
  },
  {
    "level": 30,
    "tweet": "Study microeconomics, game theory, psychology, persuasion, ethics, mathematics, and computers.",
    "sectionTitle": "The Foundations Are Math and Logic",
    "sectionIndex": 16,
    "navAlAnchor": "#the-foundations-are-math-and-logic",
    "taglines": [
      "Mathematics and logic are the basis for understanding everything else"
    ],
    "navalQuotes": [
      "Foundational things are principles, they're algorithms, they're deep seated logical understanding where you can defend it or attack it from any angle. And that's why microeconomics is important because macroeconomics is a lot of memorization, a lot of macro bullshit.",
      "Yeah. In fact let me expand that a little bit. I would say that the five most important skills are of course, reading, writing, arithmetic, and then as you're adding in, persuasion, which is talking. And then finally, I would add computer programming just because it's an applied form of arithmetic that just gets you so much leverage for free in any domain that you operate in."
    ],
    "niviQuotes": [
      "To lay a foundation for learning for the rest of your life I think you need two things, if I was going to try and sum it up. One, practical persuasion and two, you need to go deep in some technical category, whether it's abstract math, or you want to read Donald Knuth's books on algorithms, or you want to read Feynman's lectures on physics."
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 31,
    "tweet": "Reading is faster than listening. Doing is faster than watching.",
    "sectionTitle": "Read What You Love Until You Love to Read",
    "sectionIndex": 15,
    "navAlAnchor": "#read-what-you-love-until-you-love-to-read",
    "taglines": [
      "You should be able to pick up any book in the library and read it"
    ],
    "navalQuotes": [
      "Yeah, the most important tweet on this, I don't even have in here unfortunately, which is, the foundation of learning is reading. I don't know a smart person who doesn't read and read all the time."
    ],
    "niviQuotes": [
      "Before we go and talk about accountability and leverage and judgment, you've got a few tweets further down the line that I would put in the category of continuous learning."
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 32,
    "tweet": "You should be too busy to \"do coffee,\" while still keeping an uncluttered calendar.",
    "sectionTitle": "Be Too Busy to 'Do Coffee'",
    "sectionIndex": 28,
    "navAlAnchor": "#be-too-busy-to-do-coffee",
    "taglines": [
      "Ruthlessly cut meetings",
      "People will meet with you when you have proof of work",
      "Free your time and mind"
    ],
    "navalQuotes": [
      "Another tweet was: “ You should be too busy to ‘do coffee,’ while still keeping an uncluttered calendar. ”",
      "I used to have a tough time turning people down for meetings. Now I just tell them outright, “I don’t do non-transactional meetings. I don’t do meetings without a strict agenda. I don’t do meetings unless we absolutely have to.”"
    ],
    "niviQuotes": [
      "“Doing coffee” reminds me of an old quote, I think from Steve Jobs, when someone asked him why Apple didn’t come to a convention. His response was something like, “Because we wouldn’t be here working.”"
    ],
    "tweetQuotesFromDialogue": [
      "You should be too busy to ‘do coffee,’ while still keeping an uncluttered calendar.",
      "reminds me of an old quote, I think from Steve Jobs, when someone asked him why Apple didn’t come to a convention. His response was something like,",
      "I don’t do non-transactional meetings. I don’t do meetings without a strict agenda. I don’t do meetings unless we absolutely have to."
    ]
  },
  {
    "level": 33,
    "tweet": "Set and enforce an aspirational personal hourly rate. If fixing a problem will save less than your hourly rate, ignore it. If outsourcing a task will cost less than your hourly rate, outsource it.",
    "sectionTitle": "Set an Aspirational Hourly Rate",
    "sectionIndex": 26,
    "navAlAnchor": "#set-an-aspirational-hourly-rate",
    "taglines": [
      "Outsource tasks that cost less than your hourly rate"
    ],
    "navalQuotes": [
      "No one is going to value you more than you value you. Set a high personal hourly rate, and stick to it. When I was young, I decided I was worth a lot more than the market thought I was worth. And I started treating myself that way."
    ],
    "niviQuotes": [
      "We covered the skills you need to get rich. They included specific knowledge, accountability, leverage, judgment and life-long learning. Let’s talk about the importance of working hard and valuing your time."
    ],
    "tweetQuotesFromDialogue": []
  },
  {
    "level": 34,
    "tweet": "Work as hard as you can. Even though who you work with and what you work on are more important than how hard you work.",
    "sectionTitle": "Work As Hard As You Can",
    "sectionIndex": 27,
    "navAlAnchor": "#work-as-hard-as-you-can",
    "taglines": [
      "Work as hard as you can",
      "What you work on and who you work with are more important",
      "No matter how high your bar is, raise it",
      "Nobody really works 80 hours a week",
      "Inspiration is perishable",
      "Impatience with actions, patience with results"
    ],
    "navalQuotes": [
      "Let’s talk about hard work. There’s a battle that happens on Twitter a lot. Should you work hard or should you not? David Heinemeier Hansson says, “It’s like you’re slave-driving people.” Keith Rabois says, “No, all the great founders worked their fingers to the bone.”"
    ],
    "niviQuotes": [],
    "tweetQuotesFromDialogue": [
      "It’s like you’re slave-driving people.",
      "No, all the great founders worked their fingers to the bone."
    ]
  },
  {
    "level": 35,
    "tweet": "Become the best in the world at what you do. Keep redefining what you do until this is true.",
    "sectionTitle": "Keep Redefining What You Do",
    "sectionIndex": 29,
    "navAlAnchor": "#keep-redefining-what-you-do",
    "taglines": [
      "Find founder-product-market fit"
    ],
    "navalQuotes": [
      "If you really want to get paid in this world, you want to be number one at whatever you do. It can be niche—that’s the point. You can literally get paid for just being you."
    ],
    "niviQuotes": [
      "We talked about the importance of working hard and valuing your time. Next, there are a few tweets on the topic of working for the long-term. The first tweet is: “ Become the best in the world at what you do. Keep redefining what you do until this is true. ”"
    ],
    "tweetQuotesFromDialogue": [
      "Become the best in the world at what you do. Keep redefining what you do until this is true."
    ]
  },
  {
    "level": 36,
    "tweet": "There are no get rich quick schemes. That's just someone else getting rich off you.",
    "sectionTitle": "There Are No Get Rich Quick Schemes",
    "sectionIndex": 35,
    "navAlAnchor": "#there-are-no-get-rich-quick-schemes",
    "taglines": [
      "We don’t have ads because it would ruin our credibility",
      "Every founder has to lie to every employee",
      "Anyone giving advice on how to get rich should have made their money elsewhere"
    ],
    "navalQuotes": [
      "This goes back to the world being an efficient place. If there’s an easy way to get rich, it’s already been exploited. There are a lot of people who will sell you ideas and schemes on how to make money. But they’re always selling you some $79.95 course or some audiobook or seminar.",
      "There’s a lot of random error in there. This is why you have to absolutely and completely ignore business journalists and economist academics when they talk about private companies.",
      "One of the reasons we’re a little vague in this podcast is because we’re trying to lay down principles that are timeless, as opposed to giving you the winning lottery ticket numbers from yesterday."
    ],
    "niviQuotes": [
      "We skipped one tweet because I wanted to cover all of the tweets on the topic of the long-term. The tweet we skipped: “ There are no get rich quick schemes. That’s just someone else getting rich off you. ”",
      "Any time you see somebody who’s gotten rich following some guru’s advice on getting rich, remember that in any random process, if you run it long enough and if enough people participate in it, you will always get every single possible outcome with probability one."
    ],
    "tweetQuotesFromDialogue": [
      "There are no get rich quick schemes. That’s just someone else getting rich off you.",
      "Fooled By Randomness ."
    ]
  },
  {
    "level": 37,
    "tweet": "Apply specific knowledge, with leverage, and eventually you will get what you deserve.",
    "sectionTitle": "Eventually You Will Get What You Deserve",
    "sectionIndex": 32,
    "navAlAnchor": "#eventually-you-will-get-what-you-deserve",
    "taglines": [
      "What are you really good at, that the market values?"
    ],
    "navalQuotes": [
      "This one is a glib way of saying, “It takes time.” Once you have all of the pieces in place, there’s still an indeterminate amount of time you have to put in. And if you’re counting, you’ll run out of patience before it arrives.",
      "That’s a really good way to summarize it. It’s worth trying to sketch that equation out."
    ],
    "niviQuotes": [
      "We’re talking about working for the long-term. The next tweet on that topic: “ Apply specific knowledge, with leverage, and eventually you will get what you deserve. ”",
      "Your eventual outcome will be equal to something like the distinctiveness of your specific knowledge; times how much leverage you can apply to that knowledge; times how often your judgment is correct; times how singularly accountable you are for the outcome; times how much society values what you’re doing. Then you compound that with how long you can keep doing it and how long you can keep improving it through reading and learning."
    ],
    "tweetQuotesFromDialogue": [
      "Apply specific knowledge, with leverage, and eventually you will get what you deserve."
    ]
  },
  {
    "level": 38,
    "tweet": "Productize yourself. Find what feels like play to you but looks like work to others, and build leverage around it.",
    "sectionTitle": "Productize Yourself",
    "sectionIndex": 36,
    "navAlAnchor": "#productize-yourself",
    "taglines": [
      "Find hobbies that make you rich, fit and creative"
    ],
    "navalQuotes": [
      "Productize has specific knowledge and leverage. Yourself has uniqueness and accountability. Yourself also has specific knowledge. So you can combine all of these pieces into these two words.",
      "Making money should be a function of your identity and what you like to do. Another tweet I really liked was, “ Find three hobbies: One that makes you money, one that keeps you fit, and one that makes you creative. ”"
    ],
    "niviQuotes": [
      "You summarized this entire tweetstorm with two words: “ Productize yourself. ”",
      "You want to figure out what you’re uniquely good at—or what you uniquely are— and apply as much leverage as possible. So making money isn’t even something you do. It’s not a skill. It’s who you are, stamped out a million times."
    ],
    "tweetQuotesFromDialogue": [
      "Productize yourself.",
      "Find three hobbies: One that makes you money, one that keeps you fit, and one that makes you creative."
    ]
  },
  {
    "level": 39,
    "tweet": "When you're finally wealthy, you'll realize that it wasn't what you were seeking in the first place. But that's for another day.",
    "sectionTitle": "A Calm Mind, a Fit Body, a House Full of Love",
    "sectionIndex": 34,
    "navAlAnchor": "#a-calm-mind-a-fit-body-a-house-full-of-love",
    "taglines": [
      "A calm mind, a fit body and a house full of love must be earned",
      "Practical advice for a calmer internal state",
      "A lot of divorces happen over money, a lot of battles happen over internal anger"
    ],
    "navalQuotes": [
      "That’s a multi-hour topic in and of itself. First of all, I thought it was a really clever way to end the whole thing. It disarms a whole set of people who say, “What’s the point of getting rich?” There are a lot of people who like to virtue signal against the idea of wealth creation or making money.",
      "Yeah. To me the ultimate purpose of money is so you don’t have to be in a specific place, at a specific time, doing anything you don’t want to do."
    ],
    "niviQuotes": [
      "The last tweet on the topic of working for the long-term is: “ When you’re finally wealthy, you’ll realize it wasn’t what you were seeking in the first place. But that’s for another day. ”",
      "To summarize: Money solves your money problems. Money buys you freedom in the material world. And money lets you not do the things you don’t want to do."
    ],
    "tweetQuotesFromDialogue": [
      "When you’re finally wealthy, you’ll realize it wasn’t what you were seeking in the first place. But that’s for another day.",
      "What’s the point of getting rich?"
    ]
  }
];

export function getNavalRichLevel(levelId: number): NavalRichLevel | undefined {
  return NAVAL_RICH_LEVELS.find((l) => l.level === levelId);
}

export function getCanonicalTweet(levelId: number): string | undefined {
  return getNavalRichLevel(levelId)?.tweet;
}

export function navAlSectionUrl(levelId: number): string {
  const row = getNavalRichLevel(levelId);
  if (!row) return NAVAL_RICH_SOURCE_URL;
  return `${NAVAL_RICH_SOURCE_URL}${row.navAlAnchor}`;
}
